feat: dockerised Frontend-22 for prod
delta/Festember-frontend-2022 pull request #92
Opened 2023-04-08 10:40 UTC by ZaBarudo

2023-04-08 11:59 UTC, Hedhav requested changes
Add new lines at EOF

Space out the Dockerfile better

2023-04-08 11:59 UTC, Hedhav commented on Dockerfile
> +WORKDIR /app
WORKDIR is typically specified right under the `FROM <image_name>` line

2023-04-08 11:59 UTC, Hedhav commented on Dockerfile
> +CMD ["nginx", "-g", "daemon off;"]
New line at EOF

2023-04-08 11:59 UTC, Hedhav commented on docker-compose.yaml
> +    image: fest_frontend:prod
```suggestion
    image: main_site_22:prod
```

2023-04-08 11:59 UTC, Hedhav commented on docker-compose.yaml
> +    container_name: fest_frontend
```suggestion
    container_name: main_site_22
```

2023-04-09 18:15 UTC, ZaBarudo commented
@Hedhav Done making changes

2023-04-14 15:39 UTC, Hedhav requested changes
New lines in EOF please

2023-04-14 15:39 UTC, Hedhav commented on Dockerfile
> +COPY yarn.lock .
```suggestion
COPY package.json package.json
COPY yarn.lock yarn.lock
```

2023-04-14 15:39 UTC, Hedhav commented on docker-compose.yaml
> +    restart: always
Order:
    container_name
    image
    build: 
    ports:
    restart:

2023-04-19 09:15 UTC, Hedhav approved these changes

2023-04-19 09:20 UTC, Ram-20062003 approved these changes

2023-04-19 09:21 UTC, merged